sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 021218
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    bucketName: carry-javaweb-ai
    access-key-id: LTAI5tAqMfo7iGWsDb5odBCa
    access-key-secret: vo4IenTP1xqUsNGC5Z0RUszAjkiwWP
  redis:
    host: 192.168.239.200
    port: 6379
    password: 021218
    database: 0

  wechat:
      appid: wxf8d7775cabffcfdf
      secret: 91b8ae813647cf71bd2fd1f3a6fee341
      mchid: 1561414331
      mchSerialNo: 4B3B3DC35414AD50B1B755BAF8DE9CC7CF407606
      privateKeyFilePath: D:\pay\apiclient_key.pem
      apiV3Key: CZBK51236435wxpay435434323FFDuv3
      weChatPayCertFilePath: D:\pay\wechatpay_166D96F876F45C7D07CE98952A96EC980368ACFC.pem
      notifyUrl: https://6619cf50.r6.cpolar.top/notify/paySuccess
      refundNotifyUrl: https://6619cf50.r6.cpolar.top/notify/refundSuccess
  shop:
    address: 北京是海淀区上地十街10号
  baidu:
    ak: nndKv0Hr0qb9nACNjRsAx2R3y1cPhOpg